# Generated by Django 4.2.6 on 2023-10-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_price'),
        ('product_reviews', '0002_productreview_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
