# Generated by Django 4.2.6 on 2023-10-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_reviews', '0003_productreview_content_productreview_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(max_length=5, null=True),
        ),
    ]
