# Generated by Django 4.2.6 on 2023-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_reviews', '0004_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
