# Generated by Django 4.2.6 on 2023-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
