# Generated by Django 4.2.6 on 2023-10-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_price'),
        ('dibs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dib',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
